image: node:latest

stages:
  - canary
  - pre-release
  - release

before_script:
  - git submodule update --init --recursive
  - source .ci-env
  - npm install -g @nofrills/tasks@7.1.12
  - cli-tasks ci:install

cache:
  paths:
    - node_modules

continuous:
  stage: canary
  only:
    - /feature\/.*/
    - /fix\/.*/
  script:
    - cli-tasks ci:canary

prerelease:
  stage: pre-release
  only:
    - develop
  script:
    - cli-tasks ci:prerelease

release:
  stage: release
  only:
    - master
  script:
    - cli-tasks ci:release
