image: node:latest

stages:
  - canary
  - pre-release
  - release

before_script:
  - git submodule update --init -- .citools
  - source .ci-env.sh
  - npm install -g @nofrills/tasks@7.1.12
  - npm install

cache:
  paths:
    - node_modules

continuous:
  stage: canary
  only:
    - /feature\/.*/
    - /fix\/.*/
  script:
    - npm run canary

prerelease:
  stage: pre-release
  only:
    - develop
  script:
    - npm run pre-release

release:
  stage: release
  only:
    - master
  script:
    - npm run release
