image: node:latest

stages:
  - canary
  - pre-release
  - release

cache:
  paths:
    - node_modules

before_script:
  - git submodule update --init -- .citools
  - source .ci-env.sh
  - npm install -g @nofrills/tasks@7.1.12
  - npm install
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc

continuous:
  stage: canary
  only:
    - /feature\/.*/
    - /fix\/.*/
  script:
    - npm run canary
  artifacts:
    paths:
      - packages/tinyvault/binaries

prerelease:
  stage: pre-release
  only:
    - develop
  script:
    - npm run pre-release
  artifacts:
    paths:
      - packages/tinyvault/binaries

release:
  stage: release
  only:
    - master
  script:
    - npm run release
  artifacts:
    paths:
      - packages/tinyvault/binaries
